Update intl_ja.arb
Notsfsssf/pixez-flutter pull request #216
Opened 2021-06-07 09:51 UTC by YooTynChi

2021-06-07 18:50 UTC, itzXian requested changes

2021-06-07 18:50 UTC, itzXian commented on lib/l10n/intl_ja.arb
> +  "old_way": "本来のやり方",
`"old_way": "レガシー",`

2021-06-07 18:50 UTC, itzXian commented on lib/l10n/intl_ja.arb
> +  "follow_after_star":"作品をお気に入りに追加したら作者をフォローする",
`"follow_after_star":"作品をお気に入りに追加したら作者もフォローする",`

2021-06-07 18:50 UTC, itzXian commented on lib/l10n/intl_ja.arb
> +  "manga_detail_page_quality":"漫画詳細ページの画質について",
`"manga_detail_page_quality":"マンガ詳細ページの画質について",`

2021-06-07 18:50 UTC, itzXian commented on lib/l10n/intl_ja.arb
> +  "about": "ついて",
`"about": "PixEzについて",`

2021-06-07 18:50 UTC, itzXian commented on lib/l10n/intl_ja.arb
>    "more": "もっと見る",
`"more": "もっと",`

2021-06-07 18:50 UTC, itzXian commented on lib/l10n/intl_ja.arb
>    "legacy_mode_warning": "android10以降では推奨しません",
`"legacy_mode_warning": "Android 10以降では推奨しません",`

2021-06-07 19:18 UTC, itzXian commented
お疲れ様でしたぁ
失礼ながら個人的な考えでReviewさせて頂きます、よろしければ一緒に検討しませんか?

2021-06-07 19:19 UTC, itzXian commented
お疲れ様でしたぁ
そして失礼ながら個人的な考えでReviewさせて頂きます、よろしければ一緒に検討しませんか?

2021-06-08 04:27 UTC, YooTynChi commented
我的塑料工地日语被发现了www（捂脸

@itzXian 非常感谢您的review。已经改正并提交新的commit。

2021-06-09 14:51 UTC, Notsfsssf commented
Gj,希望持续支持

2021-06-09 14:51 UTC, merged